@id = 0202

@authToken = {{loginAdmin.response.headers.X-AuthToken}}

###
# @name loginAdmin
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "username": "admin",
  "password": "admin"
}
###

# @name GetMyReservations
get {{baseUri}}/reservations/user
Authorization: bearer {{authToken}}