

@id = 0202

@authToken = {{loginAdmin.response.headers.X-AuthToken}}

###
# @name loginAdmin
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "username": "admin",
  "password": "admin"
}
###
# @name GetItemReservations
get {{baseUri}}/reservations/{{id}}
Authorization: bearer {{authToken}}