@authToken = {{loginAdmin.response.headers.X-AuthToken}}

###
# @name loginAdmin
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "username": "admin",
  "password": "admin"
}

###
# @name register
POST {{baseUri}}/auth/register
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "testsson",
  "username": "test",
  "email": "test@test.com",
  "password": "test",
  "validatePassword": "test"
}