@baseUrl = https://localhost:7065/api

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}

###

@authToken = {{login.response.body}}

# @name libris
GET {{baseUrl}}/Libris
Authorization: {{authToken}}