@authToken = {{loginAdmin.response.headers.X-AuthToken}}

###
# @name loginAdmin
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "username": "admin",
  "password": "admin"
}

###
# @name AddItemInventory
POST {{baseUri}}/inventory
Authorization: bearer {{authToken}}
Content-Type: application/json

{
    "ItemId": 992392,
    "AmountToAdd": 10
}

###
# @name DeleteItemInventory
DELETE {{baseUri}}/Inventory/5
Content-Type: application/json

{
    "InventoryId": 5
}

###
# @name GetItemInventory
GET {{baseUri}}/Inventory/10
Authorization: bearer {{authToken}}