@authToken = {{loginAdmin.response.headers.X-AuthToken}}

###
# @name loginAdmin
POST {{baseUri}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "username": "admin",
  "password": "admin"
}

###
# @name getItems
GET {{baseUri}}/items

###
# @name getItem
GET {{baseUri}}/items/1

###
# @name deleteItem
DELETE {{baseUri}}/items/1

###
# @name getItem
GET {{baseUri}}/items/10000