@authToken = {{loginAdmin.response.headers.X-AuthToken}}

###
# @name loginAdmin
POST {{baseUri}}/auth/login
Content-Type: application/json


{
  "email": "jaff@gmail.com",
  "username": "jaff",
  "password": "jaff"
}

# {
#   "email": "admin@gmail.com",
#   "username": "admin",
#   "password": "admin"
# }

###
# @name loans
GET {{baseUri}}/loans
Authorization: Bearer {{authToken}}

###
# @name loans
POST {{baseUri}}/loans
Content-Type: application/json


[
  {
    "ItemId":4,
    "Title": "Hej",
    "Description" : "dkasd"
  }
]


###
# @name loans/user
GET {{baseUri}}/loans/user
Authorization: Bearer {{authToken}}

###
# @name loans/id
DELETE {{baseUri}}/loans/2
Authorization: Bearer {{authToken}}



